# https://developers.cloudflare.com/workers/wrangler/configuration

[[d1_databases]]
binding = "DB_Sources" # i.e. available in your Worker on env.DB
database_name = "Sources.2023-12-04"
database_id = "8632cf2f-fb55-4e31-a23a-1bc0c84c9c78"
