# https://developers.cloudflare.com/workers/wrangler/configuration

# https://developers.cloudflare.com/workers/wrangler/configuration/#custom-builds
[build]
command = "pnpm build"

[[d1_databases]]
binding = "DB_Sources" # i.e. available in your Worker on env.DB
database_name = "Sources.2024-03-11"
database_id = "a3ddaf2f-d49d-43fb-9d6b-daeb155f6c05"

